import {
  spacex,
  persica,
  holidaze,
  reactprojects,
  wowfood,
  moderngpt,
  plantex,
} from "./imports";

export const ProjectItems = [
  {
    title: "SpaceX",
    type: "School Project",
    url: "https://spacex-projectexam.vercel.app/",
    btnText: "Visit Website",
    image: spacex,
    tags: ["Design ▪️ ", "HTML ▪️ ", "CSS ▪️ ", "JavaScript ▪️ ", "API"],
    cName: "projects__list__item",
  },
  {
    title: "PERSICA",
    type: "School Project",
    url: "https://persica-skincare.vercel.app/",
    btnText: "Visit Website",
    image: persica,
    tags: [
      "Design ▪️ ",
      "Branding ▪️ ",
      "HTML ▪️ ",
      "Sass ▪️ ",
      "JavaScript ▪️ ",
      "API ▪️ ",
      "Bootstrap ▪️ ",
      "Strapi",
    ],
    cName: "projects__list__item",
  },
  {
    title: "Holidaze",
    type: "School Project",
    url: "https://holidaze-norway.vercel.app/",
    btnText: "Visit Website",
    image: holidaze,
    tags: [
      "Design ▪️ ",
      "React JS ▪️ ",
      "Sass ▪️ ",
      "Bootstrap ▪️ ",
      "BEM ▪️ ",
      "Strapi",
    ],
    cName: "projects__list__item",
  },
  {
    title: "15 React Projects",
    type: "Private Project",
    url: "https://15-react-projects.vercel.app/",
    btnText: "Visit Website",
    image: reactprojects,
    tags: ["React JS ▪️ ", "Sass ▪️ ", "BEM ▪️ ", "Design ▪️ ", "API"],
    cName: "projects__list__item",
  },
  {
    title: "wowFood",
    type: "Private Project",
    url: "https://github.com/frontalexandraep/wowFood",
    btnText: "Visit GitHub",
    image: wowfood,
    tags: ["PHP ▪️ ", "CSS ▪️ ", "MySQL ▪️ ", "Frontend ▪️ ", "Backend"],
    cName: "projects__list__item",
  },
  {
    title: "GPT-3",
    type: "Private Project",
    url: "https://modern-gpt3.vercel.app/",
    btnText: "Visit Website",
    image: moderngpt,
    tags: ["React JS ▪️ ", "CSS ▪️ ", "JSX ▪️ ", "BEM ▪️ ", "Design"],
    cName: "projects__list__item",
  },
  {
    title: "PLANTEX",
    type: "Private Project",
    url: "https://plantex.vercel.app/",
    btnText: "Visit Website",
    image: plantex,
    tags: ["HTML ▪️ ", "CSS ▪️ ", "JS ▪️ ", "Design ▪️ ", "Modern ▪️ ", "Responsive"],
    cName: "projects__list__item",
  },
];
